### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by dzzzzzy** [nest-cloud/nestcloud#1]
I am a nestjs developer, and working on a lot of micro-service system. This nest micro-service solution is very awesome, so I am looking forward to contribute to this project.

Looking forward to your reply :heart:

**Comment by miaowing** [comment]
I have invited you. I will migrate the sub projects into this group in the future.😁

**Comment by dzzzzzy** [comment]
@miaowing Thanks a lot. Could you send me your qq or wechat to my email: `insistyao_0522@163.com` ?
