### ISSUE TITLE
import { IConsulService } from '@nestcloud/common';

### ISSUE THREAD

**Issue by wzch333** [nest-cloud/nestcloud#11]

**Comment by wzch333** [comment]
node_modules/@nestcloud/consul-service/consul-service.class.d.ts:3:10 - error TS2305: Module '"../common"' has no exported member 'IConsulService'.

**Comment by miaowing** [comment]
Use the latest version 0.5.2 and use `@nestcloud/service` instead `@nestcloud/consul-service`.

Some packages are renamed in the latest version:

`@nestcloud/boot`
`@nestcloud/common`
`@nestcloud/config`
`@nestcloud/consul`
`@nestcloud/core`
`@nestcloud/feign`
`@nestcloud/grpc`
`@nestcloud/kubernetes`
`@nestcloud/loadbalance`
`@nestcloud/logger`
`@nestcloud/proxy`
`@nestcloud/schedule`
`@nestcloud/service`
