### ISSUE TITLE
TypeError: Cannot read property 'choose' of undefined

### ISSUE THREAD

**Issue by oak-c** [nest-cloud/nestcloud#15]
TypeError: Cannot read property 'choose' of undefined

My app.module.ts like this:
        LoggerModule.register(),
        BootModule.register(context, filename),
        ConsulModule.register({ dependencies: [NEST_BOOT] }),
        LoadbalanceModule.register({ dependencies: [NEST_BOOT] }),
        ConfigModule.register({ dependencies: [NEST_BOOT, NEST_CONSUL] }),
        ProxyModule.register({ dependencies: [NEST_BOOT] }),

**Comment by miaowing** [comment]
Can you provide me more message？Or you can start your project by a starter:

[nestcloud-consul-starter](https://github.com/nest-cloud/nestcloud-consul-starter)

[nestcloud-etcd-starter](https://github.com/nest-cloud/nestcloud-etcd-starter)

**Comment by oak-c** [comment]
> Can you provide me more message？Or you can start your project by a starter:
> 
> [nestcloud-consul-starter](https://github.com/nest-cloud/nestcloud-consul-starter)
> 
> [nestcloud-etcd-starter](https://github.com/nest-cloud/nestcloud-etcd-starter)
 

Thanks for your reply.
nestcloud-consul-starter  post  http://127.0.0.1:8081/proxy/user/

**Comment by miaowing** [comment]
proxy module need inject NEST_LOADBALANCE，I have modified the starter, thank you.

then, get http://127.0.0.1:8081/proxy/user/users

```typescript
ProxyModule.register({ dependencies: [NEST_BOOT, NEST_LOADBALANCE] }),
```

**Comment by Alexlz2538** [comment]
请问下 ，上面这个UI界面是nestcloud-consul-starter 自带的吗
