### ISSUE TITLE
Is nest-cloud/validations deprecated?

### ISSUE THREAD

**Issue by fabiofdsantos** [nest-cloud/nestcloud#17]
I've noticed that [nest-cloud/validations](https://github.com/nest-cloud/validations) is archived. Is this deprecated?

The package is still being used in samples and `nestcloud-typeorm-example` repo.

**Comment by miaowing** [comment]
Thank you, the `@nestcloud/validations` module will release separately and remove from this repository

https://github.com/nest-cloud/validations
