### ISSUE TITLE
Documentation out of date ? For example - missing methods

### ISSUE THREAD

**Issue by iangregsondev** [nest-cloud/nestcloud#19]
Hi,

I just tried bootstrapping a simple application as per the readme. But I am getting missing type, missing methods.

Can you please help?

Here is an image explaining the issue

![image](https://user-images.githubusercontent.com/2370364/78449947-40e49a80-767b-11ea-8c9e-9e166439a7ce.png)

**Comment by miaowing** [comment]
You can check your package.json, wether the version of @nestcloud/xxx  is 0.7.x or not.

**Comment by iangregsondev** [comment]
Hi - thanks for getting back to me - yes that is correct, they are 0.6

```
    "@nestcloud/common": "^0.6.11",
    "@nestcloud/consul": "^0.6.11",
    "@nestcloud/service": "^0.6.11",
```

In NPM the latest tag hasn't been updated, here's consul for example.

https://www.npmjs.com/package/@nestcloud/consul

I did a standard NPM install from nothing - so it took the latest tag from npm.

is 0.7 classified as a beta and 0.6 not then ?

I should upgrade then - correct ?

**Comment by iangregsondev** [comment]
I notice there is a NEXT and BETA - is there a difference ?

One suggested over the other ?

**Comment by miaowing** [comment]
Yeah, 0.7.x is already a beta version😅

**Comment by iangregsondev** [comment]
Ok - thanks. I have it working now :-)
