### ISSUE TITLE
@nestcloud/feign 0.3.15包引用

### ISSUE THREAD

**Issue by mjj18272173737** [nest-cloud/nestcloud#4]
feign.module.ts中引用了import { NEST_CONSUL_CONFIG_PROVIDER } from '../common'，应该是import { NEST_CONSUL_CONFIG_PROVIDER } from '@nestcloud/common';

**Comment by mjj18272173737** [comment]
npm安装没问题，cnpm安装会把@nestcloud的包分开就会出错

**Comment by miaowing** [comment]
非常感谢，已经 Fix 了 @mjj18272173737
