### ISSUE TITLE
我现在使用grpc，某个server异常情况下，Loadbalance不会再发现该服务

### ISSUE THREAD

**Issue by mjj18272173737** [nest-cloud/nestcloud#9]
某个server的某部分功能有异常，但是此时loadbalance中

![1569377776(1)](https://user-images.githubusercontent.com/12655134/65563857-8e21da00-df7d-11e9-913a-e627f6ce0c86.png)
![1569378180(1)](https://user-images.githubusercontent.com/12655134/65564112-7b5bd500-df7e-11e9-98e9-2b18bb2ddb9d.png)

**Comment by miaowing** [comment]
感谢，代码里缺少server不存在的时候的检测，之后我会加上。
默认规则 server 状态只有在 passing 的时候才可以被发现，如果有需求可以自定义 LB 规则。

```typescript
import { Rule, Loadbalancer } from '@nestcloud/loadbalance';

export class CustomRule implements Rule {
    private loadbalancer: Loadbalancer;
    
    init(loadbalancer: Loadbalancer) {
        this.loadbalancer = loadbalancer;
    }

    choose() {
        const servers = this.loadbalancer.servers;
        return servers[0];
    }
}
```

```typescript
import { Module } from '@nestjs/common';
import { LoadbalanceModule } from '@nestcloud/loadbalance';

@Module({
  imports: [
      LoadbalanceModule.register({customRulePath: __dirname})
  ],
})
export class ApplicationModule {}
```

**Comment by mjj18272173737** [comment]
恩，这只能解决一部分问题。还要就是最后一次调用时更新异常状态感觉有些问题，要区分是服务不可用还是服务异常（代码有bug，但是肯定是可以继续使用的），现在是有任何异常都把服务state设置为critical，我觉得应该是服务不可用时设置为critical
